package com.example.servertech.domain.user.repository;

import com.example.servertech.domain.user.entity.User;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserRepository implements UserRepository {
	private final List<User> data = Collections.synchronizedList(new ArrayList<>());
	private final AtomicLong autoGeneratedId = new AtomicLong(1);

	@Override
	public User save(User user) {
		User build = User.builder()
			.id(autoGeneratedId.getAndIncrement())
			.name(user.getName())
			.email(user.getEmail())
			.password(user.getPassword())
			.role(user.getRole())
			.build();
		data.add(build);
		return build;
	}

	@Override
	public Optional<User> findById(Long id) {
		return data.stream().filter(user -> user.getId().equals(id)).findFirst();
	}

	@Override
	public Optional<User> findByEmail(String email) {
		return data.stream().filter(user -> user.getEmail().equals(email)).findFirst();
	}
}
