services:
  server-tech:
    build: .
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      postgres-db-server:
        condition: service_healthy
      redis-cache-server:
        condition: service_healthy
  postgres-db-server:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tech
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d tech" ]
      interval: 5s
      retries: 10
  redis-cache-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
  prometheus-metric-server:
    image: bitnami/prometheus
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
  grafana-monitoring-server:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana